### ISSUE TITLE
AttributeError: when running black.

### ISSUE THREAD

**Issue by SimiCode** [hukkin/tomli#171]
### tomli==2.0.0

```
Traceback (most recent call last):
  File "/Users/XYZ/venv/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/Users/XYZ/venv/lib/python3.10/site-packages/black/__init__.py", line 1130, in patched_main
    main()
  File "/Users/XYZ/venv/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/XYZ/venv/lib/python3.10/site-packages/click/core.py", line 1061, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/Users/XYZ/venv/lib/python3.10/site-packages/click/core.py", line 923, in make_context
    self.parse_args(ctx, args)
  File "/Users/XYZ/venv/lib/python3.10/site-packages/click/core.py", line 1379, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Users/XYZ/venv/lib/python3.10/site-packages/click/core.py", line 2364, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/Users/XYZ/venv/lib/python3.10/site-packages/click/core.py", line 2326, in process_value
    value = self.callback(ctx, self, value)
  File "/Users/XYZ/venv/lib/python3.10/site-packages/black/__init__.py", line 105, in read_pyproject_toml
    config = parse_pyproject_toml(value)
  File "/Users/XYZ/venv/lib/python3.10/site-packages/black/files.py", line 95, in parse_pyproject_toml
    pyproject_toml = tomli.load(f)
  File "/Users/XYZ/venv/lib/python3.10/site-packages/tomli/_parser.py", line 55, in load
    s = __fp.read().decode()
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
```

**Comment by hauntsaninja** [comment]
I think this is more a black issue, what version of black are you running?
My guess would be that you're running on an old version of black that is broken by tomli 2.0. Your options are probably to upgrade black or downgrade tomli to v1.

**Comment by SimiCode** [comment]
Exactly: This was a dependency issue

```
