### ISSUE TITLE
Lower `z` in datetime should be valid

### ISSUE THREAD

**Issue by pwwang** [hukkin/tomli#192]
```python
import rtoml
>>> rtoml.loads('t = 1987-07-05t17:45:00z')
{'t': datetime.datetime(1987, 7, 5, 17, 45, tzinfo=<builtins.TzClass object at 0x7f1892986310>)}
```

```python
import tomli
>>> tomli.loads('t = 1987-07-05t17:45:00z')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    tomli.loads('t = 1987-07-05t17:45:00z')
  File "/path/to/python3.9/site-packages/tomli/_parser.py", line 136, in loads
    raise suffixed_err(
tomli._parser.TOMLDecodeError: Expected newline or end of document after a statement (at line 1, c
olumn 15)
```

References:

- https://github.com/BurntSushi/toml-test/blob/v1.1.0/tests//valid/datetime/datetime.toml
- https://github.com/pwwang/toml-bench#testcompliancevalid

**Comment by pwwang** [comment]
Never mind. Latest version passes the tests.
